---
title: "Operations with Vectors"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Basic Operations with Vectors

This is the monthly average temperature in Baltimore (from http://www.rssweather.com/climate/Maryland/Baltimore/)

```{r}
tempHi <- c(41.2,44.8,53.9,64.5,73.9,82.7,87.2,85.1,78.2,67.0,56.3,46.0)
tempHi
```

We can label the vectors' 
elements!
```{r}
months <- c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
names(tempHi) <- months
tempHi
```

Let's also get the lowers:

```{r}
tempLo <- c(23.5,26.1,33.6,42.0,51.8,60.8,65.8,63.9,56.6,43.7,34.7,27.3)
```

Now we can do simple operations on the whole vectors.

```{r}
range <- tempHi-tempLo
range
```

Covnert it to Celsius:

```{r}
tempHiC <- (5/9) * (tempHi - 32)
tempHiC
```

Is this month too cold?

```{r}
tooCold <- (((5/9) * (tempLo - 32)) < 0)
tooCold
```

### Accessing Elements in a Vector

By indexes:

```{r}
tempHi[7] # July
tempHi[12] # December

```

By ranges:
```{r}
tempHi[7:9] # July-September
```

By lists:

```{r}
tempHi[c(11:12,1:2)] # Nov-Feb
```

By sequences:

```{r}
tempHi[seq(2,12,2)] # Even months
```
